[package]
name = "jackpot-core-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
jackpot-core-common = { path = "../jackpot-core-common" }
jackpot-core-event = { path = "../jackpot-core-event" }
jackpot-core-storage = { path = "../jackpot-core-storage" }
