[package]
name = "desktop"
version.workspace = true
edition.workspace = true

[[bin]]
name = "desktop_app"
path = "src/main.rs"

[lib]
name = "desktop"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
core-common = { path = "../core-common" }
core-event = { path = "../core-event" }
core-runtime = { path = "../core-runtime" }

